source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target 'GFDeviceExtension_Tests', :exclusive => true do
  pod "GFDeviceExtension", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
